### ISSUE TITLE
[flagd] implement in-process mode

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk-contrib#139]
As mentioned in flagd documentation of  **Creating an in-process flagd provider** [^1], the in-process provider comes with unique advantages. This issue focuses on creating a .NET implementation.
**Requirements**

- Fulfill requirements outlined by flagd in-process guideline [^1]
- Minimal external dependencies 
- Updated/New README & usage guide
- Unit & e2e tests (e2e test definitions exist [here](https://github.com/open-feature/flagd-testbed/tree/main/gherkin))

**Technical requirements**

- Build both remote and in-process providers into a single dependency (To be decided after the POC)
- Reuse existing interfaces and implementations where possible 

**Tasks**

- [x] JSON logic implementation (including custom ops)
- [x] Provider functionality (sync.proto implementation)
- [x] e2e tests for both RPC and in-process
  - e2e test already exist [here](https://github.com/open-feature/dotnet-sdk/tree/main/test/OpenFeature.E2ETests) for the SDK, start with these

[^1]: https://flagd.dev/reference/specifications/in-process-providers/

**Comment by toddbaert** [comment]
Done with https://github.com/open-feature/dotnet-sdk-contrib/pull/189
